### ISSUE TITLE
Doesn't display image

### ISSUE THREAD

**Issue by mungle** [iandoe/kirbycms-panel-imagepicker-field#1]
Getting this error

`<img src="<br />
<b>Fatal error</b>:  Call to a member function url() on a non-object in <b>D:\xampp\htdocs\kirbytest\site\templates\products.php</b> on line <b>18</b><br />`

How to solve it?

**Comment by iandoe** [comment]
Could you show the piece of code you are using to output your image's url ?

**Comment by mungle** [comment]
Solved...
in blueprint example there is  feature_img but in the php code is featured_img (with "d")
Thank you!

**Comment by iandoe** [comment]
Glad you found a way to fix it :)
